"use client";

import React from "react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { FileText, Scale, RefreshCw, AlertCircle } from "lucide-react";
import FloatingParticles from "@/components/effects/FloatingParticles";

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-[#02000f] text-white relative flex flex-col justify-between overflow-x-hidden">
      <FloatingParticles />
      <Header />

      {/* Background Glows */}
      <div className="absolute top-[10%] right-1/4 w-[500px] h-[500px] bg-indigo-600/[0.01] rounded-full blur-[120px] pointer-events-none" />

      {/* Hero Header */}
      <section className="relative pt-36 pb-8 px-6 md:px-12 max-w-4xl mx-auto w-full text-center z-10">
        <div className="mb-4 inline-flex items-center gap-1.5 border border-purple-500/20 bg-purple-950/20 px-3 py-1" style={{ borderRadius: '9999px' }}>
          <Scale className="w-3.5 h-3.5 text-purple-300 animate-pulse" />
          <span className="font-mono text-[9px] tracking-[0.25em] text-purple-300 uppercase font-bold">
            USER AGREEMENT
          </span>
        </div>
        <h1 className="font-display-lg text-4xl md:text-5xl tracking-wide uppercase text-white mt-2 mb-4 leading-tight">
          Terms of Service
        </h1>
        <p className="font-body-lg text-sm md:text-base text-text-secondary italic max-w-xl mx-auto leading-relaxed">
          Last Updated: June 7, 2026. General terms governing access to AnytimeLLM dashboards and WhatsApp APIs.
        </p>
      </section>

      {/* Content Section */}
      <section className="px-6 md:px-12 max-w-4xl mx-auto w-full z-10 mb-24 font-body-md text-xs md:text-sm text-text-secondary space-y-8 leading-relaxed">
        
        {/* Quick Summaries Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
          <div className="p-5 border border-border-subtle bg-[#070518]/40 backdrop-blur-sm" style={{ borderRadius: 'var(--radius-lg)' }}>
            <FileText className="w-5 h-5 text-purple-400 mb-3" />
            <h3 className="font-display-lg text-xs uppercase tracking-wider text-white font-bold mb-2">Usage Rights</h3>
            <p className="text-[11px] text-text-secondary">
              Subject to tier subscription limits, we grant a non-exclusive license to link your WhatsApp numbers and upload catalogs.
            </p>
          </div>
          <div className="p-5 border border-border-subtle bg-[#070518]/40 backdrop-blur-sm" style={{ borderRadius: 'var(--radius-lg)' }}>
            <RefreshCw className="w-5 h-5 text-purple-400 mb-3" />
            <h3 className="font-display-lg text-xs uppercase tracking-wider text-white font-bold mb-2">Subscription & Renewal</h3>
            <p className="text-[11px] text-text-secondary">
              Billing cycles occur monthly or yearly. Active accounts auto-renew unless cancelled at least 24 hours prior.
            </p>
          </div>
          <div className="p-5 border border-border-subtle bg-[#070518]/40 backdrop-blur-sm" style={{ borderRadius: 'var(--radius-lg)' }}>
            <AlertCircle className="w-5 h-5 text-purple-400 mb-3" />
            <h3 className="font-display-lg text-xs uppercase tracking-wider text-white font-bold mb-2">Liability Limits</h3>
            <p className="text-[11px] text-text-secondary">
              We are not liable for sales drops, user API bans by Meta, or catalog inaccuracies generated by AI text completions.
            </p>
          </div>
        </div>

        {/* Detailed Terms Container */}
        <div className="border border-border-subtle bg-[#070518]/30 p-8 md:p-10 space-y-8" style={{ borderRadius: 'var(--radius-xl)' }}>
          
          <div className="space-y-3">
            <h2 className="font-display-lg text-sm md:text-base uppercase tracking-widest text-white font-bold border-b border-border-subtle/50 pb-2">
              1. Acceptance of Terms
            </h2>
            <p>
              By registering an account on AnytimeLLM or utilizing our WhatsApp automation webhooks, you agree to comply with and be bound by these Terms of Service. If you are accepting these terms on behalf of a retail business, restaurant, B2B wholesale operation, or other commercial entity, you warrant that you hold sufficient executive authority to bind such entity.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="font-display-lg text-sm md:text-base uppercase tracking-widest text-white font-bold border-b border-border-subtle/50 pb-2">
              2. Account Credentials & Security
            </h2>
            <p>
              You are responsible for safeguarding your administrative console credentials. Any operations performed within your tenant workspace are considered authorized by you. You agree to immediately notify AnytimeLLM team of any unauthorized access, API key leaks, or security compromises of your webhook verify tokens.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="font-display-lg text-sm md:text-base uppercase tracking-widest text-white font-bold border-b border-border-subtle/50 pb-2">
              3. WhatsApp API Integration & Third-Party Terms
            </h2>
            <p>
              To connect your AI assistant live, you must utilize Meta Cloud API keys or Twilio connection webhooks. You agree to:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Strictly adhere to Meta's WhatsApp Business Policy and Terms of Service.</li>
              <li>Avoid utilizing the AI chatbot to distribute unsolicited spam messages or sell prohibited items.</li>
              <li>Acknowledge that Meta maintains final authority over phone status and API throttling. AnytimeLLM holds zero liability for Meta account bans or phone status flags.</li>
            </ul>
          </div>

          <div className="space-y-3">
            <h2 className="font-display-lg text-sm md:text-base uppercase tracking-widest text-white font-bold border-b border-border-subtle/50 pb-2">
              4. Accuracy of AI-Generated Catalog Responses
            </h2>
            <p>
              AnytimeLLM utilizes advanced retrieval-augmented generation (RAG) models to formulate conversational answers based on your uploaded files.
            </p>
            <p className="italic">
              While we optimize chunk retrieval and SQL tool logic, you acknowledge that AI models can occasionally produce hallucinations or write wrong prices. You are responsible for auditing your catalog data regularly. AnytimeLLM is not responsible for pricing disputes, inventory discrepancies, or wrong order parameters answered by the bot.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="font-display-lg text-sm md:text-base uppercase tracking-widest text-white font-bold border-b border-border-subtle/50 pb-2">
              5. Support & Refund Policy
            </h2>
            <p>
              Starter and Growth tiers receive email support. Agency tier includes dedicated uptime managers. Because we offer a 14-day free trial on all plans, all sales are final upon billing cycle renewal, and we do not issue partial refunds for mid-month cancellations.
            </p>
          </div>

        </div>

      </section>

      <Footer />
    </div>
  );
}
